In [21]:
import torch

In [22]:
import numpy as np
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [23]:
inputs = torch.tensor(inputs)
targets = torch.tensor(targets)

In [24]:
type(inputs)

torch.Tensor

In [25]:
from torch.utils.data import TensorDataset

In [26]:
train_ds = TensorDataset(inputs,targets)

In [27]:
train_ds[:]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 74.,  66.,  43.],
         [ 91.,  87.,  65.],
         [ 88., 134.,  59.],
         [101.,  44.,  37.],
         [ 68.,  96.,  71.],
         [ 73.,  66.,  44.],
         [ 92.,  87.,  64.],
         [ 87., 135.,  57.],
         [103.,  43.,  36.],
         [ 68.,  97.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 57.,  69.],
         [ 80., 102.],
         [118., 132.],
         [ 21.,  38.],
         [104., 118.],
         [ 57.,  69.],
         [ 82., 100.],
         [118., 134.],
         [ 20.,  38.],
         [102., 120.]]))

In [28]:
from torch.utils.data import DataLoader
batch_size=5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [29]:
for x,y in train_dl:
    print(x)
    print(y)
    break

tensor([[ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [101.,  44.,  37.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.]])
tensor([[119., 133.],
        [103., 119.],
        [ 21.,  38.],
        [ 22.,  37.],
        [ 81., 101.]])


In [30]:
import torch.nn as nn

In [31]:
model = nn.Linear(3,2)
print(model.parameters())

<generator object Module.parameters at 0x0000019AEA950660>


In [32]:
import torch.nn.functional as F

In [33]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [34]:
def fit(epochs,model,loss_fn,opt, train_dl):
    for epoch in range(epochs):
        for x,y in train_dl:
            pred = model(x)
            loss = loss_fn(pred,y)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1)%10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, epochs, loss.item()))


In [35]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100], Loss: 546.6038
Epoch [20/100], Loss: 59.3757
Epoch [30/100], Loss: 199.5271
Epoch [40/100], Loss: 211.8099
Epoch [50/100], Loss: 44.4522
Epoch [60/100], Loss: 56.3362
Epoch [70/100], Loss: 90.4253
Epoch [80/100], Loss: 52.4571
Epoch [90/100], Loss: 29.8619
Epoch [100/100], Loss: 35.3834


In [36]:
model(torch.tensor([75,63,44.]))

tensor([54.8819, 68.5767], grad_fn=<AddBackward0>)