In [1]:
import torch

In [2]:
import numpy as np
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

In [3]:
inputs = torch.tensor(inputs)
targets = torch.tensor(targets)

In [4]:
type(inputs)

torch.Tensor

In [5]:
from torch.utils.data import TensorDataset

In [6]:
train_ds = TensorDataset(inputs,targets)

In [7]:
train_ds[:]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 74.,  66.,  43.],
         [ 91.,  87.,  65.],
         [ 88., 134.,  59.],
         [101.,  44.,  37.],
         [ 68.,  96.,  71.],
         [ 73.,  66.,  44.],
         [ 92.,  87.,  64.],
         [ 87., 135.,  57.],
         [103.,  43.,  36.],
         [ 68.,  97.,  70.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 57.,  69.],
         [ 80., 102.],
         [118., 132.],
         [ 21.,  38.],
         [104., 118.],
         [ 57.,  69.],
         [ 82., 100.],
         [118., 134.],
         [ 20.,  38.],
         [102., 120.]]))

In [8]:
from torch.utils.data import DataLoader
batch_size=5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [9]:
for x,y in train_dl:
    print(x)
    print(y)
    break

tensor([[ 73.,  67.,  43.],
        [ 88., 134.,  59.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [103.,  43.,  36.]])
tensor([[ 56.,  70.],
        [118., 132.],
        [ 57.,  69.],
        [ 80., 102.],
        [ 20.,  38.]])


In [10]:
import torch.nn as nn

In [11]:
model = nn.Linear(3,2)
print(model.parameters())

<generator object Module.parameters at 0x0000029801D9B840>


In [12]:
import torch.nn.functional as F

In [13]:
loss_fn = F.mse_loss

In [14]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [15]:
def fit(epochs,model,loss_fn,opt, train_dl):
    for epoch in range(epochs):
        for x,y in train_dl:
            pred = model(x)
            loss = loss_fn(pred,y)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if (epoch+1)%10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, epochs, loss.item()))


In [16]:
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100], Loss: 40.5102
Epoch [20/100], Loss: 50.0063
Epoch [30/100], Loss: 25.8434
Epoch [40/100], Loss: 17.5463
Epoch [50/100], Loss: 12.3697
Epoch [60/100], Loss: 8.9095
Epoch [70/100], Loss: 9.4796
Epoch [80/100], Loss: 5.7298
Epoch [90/100], Loss: 4.4093
Epoch [100/100], Loss: 3.0866


In [17]:
model(torch.tensor([75,63,44.]))

tensor([54.2164, 67.7145], grad_fn=<AddBackward0>)